/** Auto-generated by packages/dataset/scripts/gen-material-domains.mts — do not edit by hand.
 * Domain + weekday rotation for each domain-farmed material, for the Farmable calendar (D). */
export interface MaterialDomain {
  domain: string;
  days: string[];
  kind: "talent" | "weapon";
}
export const MATERIAL_DOMAINS: Record<string, MaterialDomain> = {
  "Afterglow of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Fragment": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Inheritance": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Replica": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Wish": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Aureate Radiance of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Bit of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blaze of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Hesitance": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Resolve": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Splendor": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Terror": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Broken Fang": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Cracked Tooth": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Milk Tooth": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Nostalgia": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Broken Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Chains of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Chapter of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Chunk of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Copper Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Coral Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Debris of Decarabian's City": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Decadence of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Demeanor of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Desolation of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Divinity of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Divine Body from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Dream of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Dream of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Dross of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Echo of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Echo of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Ember of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Essence of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Fetters of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Flare of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Fragment of Decarabian's Epic": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Fragment of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Golden Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Golden Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Golden Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Grain of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Guide to Admonition": {
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Ballad": {
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Conflict": {
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Contention": {
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Diligence": {
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Elegance": {
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Elysium": {
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Equity": {
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Freedom": {
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Gold": {
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Ingenuity": {
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Justice": {
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Kindling": {
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Light": {
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Moonlight": {
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Order": {
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Praxis": {
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Prosperity": {
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Resistance": {
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Transience": {
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Vagrancy": {
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Iron Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Jade Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Jeweled Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Luminous Sands from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Lustrous Stone from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the Kijin": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the One-Horned": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the Tiger's Bite": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the Wicked Lieutenant": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Gold Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Lead Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Mercury Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Primo Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Movement of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Affection": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Joy": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Valor": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Wisdom": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Augury": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Consideration": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Premonition": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Revelation": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Kindness": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Mourning": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Reminiscence": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Truth": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oblation of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Olden Days of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Philosophies of Admonition": {
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Ballad": {
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Conflict": {
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Contention": {
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Diligence": {
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Elegance": {
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Elysium": {
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Equity": {
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Freedom": {
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Gold": {
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Ingenuity": {
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Justice": {
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Kindling": {
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Light": {
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Moonlight": {
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Order": {
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Praxis": {
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Prosperity": {
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Resistance": {
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Transience": {
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Vagrancy": {
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Piece of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Relic from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Remnant Glow of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Scattered Piece of Decarabian's Dream": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Shackles of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Silver Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Silver Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Spring of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Sublimation of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Sundered Glory of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Teachings of Admonition": {
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Ballad": {
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Conflict": {
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Contention": {
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Diligence": {
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Elegance": {
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Elysium": {
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Equity": {
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Freedom": {
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Gold": {
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Ingenuity": {
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Justice": {
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Kindling": {
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Light": {
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Moonlight": {
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Order": {
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Praxis": {
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Prosperity": {
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Resistance": {
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Transience": {
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Vagrancy": {
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Tile of Decarabian's Tower": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Unyielding Delusion of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Wine Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  }
};

/** Each character's talent-book domain, for the Farmable calendar. */
export const CHARACTER_TALENT_DOMAINS: Record<string, { book: string; domain: string; days: string[] }> = {
  "aino": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "albedo": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "alhaitham": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "aloy": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "amber": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "arataki-itto": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "arlecchino": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "baizhu": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "barbara": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "beidou": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "bennett": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "candace": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "charlotte": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "chasca": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "chevreuse": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "chiori": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "chongyun": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "citlali": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "clorinde": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "collei": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "columbina": {
    "book": "Philosophies of Moonlight",
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "cyno": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "dahlia": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "dehya": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "diluc": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "diona": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "dori": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "durin": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "emilie": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "escoffier": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "eula": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "faruzan": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "fischl": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "flins": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "freminet": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "furina": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "gaming": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "ganyu": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "gorou": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "hu-tao": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "iansan": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "ifa": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "illuga": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "ineffa": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "jahoda": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "jean": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kachina": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "kaedehara-kazuha": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kaeya": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "kamisato-ayaka": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kamisato-ayato": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kaveh": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "keqing": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "kinich": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kirara": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "klee": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "kujou-sara": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kuki-shinobu": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "lan-yan": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "lauma": {
    "book": "Philosophies of Moonlight",
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "layla": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "linnea": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lisa": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lohen": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "lynette": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lyney": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "mavuika": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "mika": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "mona": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "mualani": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "nahida": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "navia": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "nefer": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "neuvillette": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "nicole": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "nilou": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "ningguang": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "noelle": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "ororon": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "prune": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "qiqi": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "raiden-shogun": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "razor": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "rosaria": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sandrone": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sangonomiya-kokomi": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sayu": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sethos": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "shenhe": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "shikanoin-heizou": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sigewinne": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "skirk": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sucrose": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "tartaglia": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "thoma": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "tighnari": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "varesa": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "varka": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "venti": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "wanderer": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "wriothesley": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "xiangling": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "xianyun": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "xiao": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "xilonen": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "xingqiu": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "xinyan": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "yae-miko": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "yanfei": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "yaoyao": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "yelan": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "yoimiya": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "yumemizuki-mizuki": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "yun-jin": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "zhongli": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "zibai": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  }
};

/** Each weapon's ascension-material domain, for the Farmable calendar. */
export const WEAPON_DOMAINS: Record<string, { domain: string; days: string[] }> = {
  "the-catch": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "ultimate-overlord-s-mega-magic-sword": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "a-teaspoon-of-transcendence": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "a-thousand-blazing-suns": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "a-thousand-floating-dreams": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "absolution": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "akuoumaru": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "alley-hunter": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "amenoma-kageuchi": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "amos-bow": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "angelos-heptades": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "aqua-simulacra": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "aquila-favonia": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "ash-graven-drinking-horn": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "astral-vulture-s-crimson-plumage": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "athame-artis": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "azurelight": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "ballad-of-the-boundless-blue": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "ballad-of-the-fjords": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "beacon-of-the-reed-sea": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "black-tassel": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "blackcliff-agate": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "blackcliff-longsword": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "blackcliff-pole": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "blackcliff-slasher": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "blackcliff-warbow": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "blackmarrow-lantern": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "bloodsoaked-ruins": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "bloodtainted-greatsword": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "calamity-of-eshu": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "calamity-queller": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "cashflow-supervision": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "chain-breaker": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "cinnabar-spindle": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "cloudforged": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "compound-bow": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "cool-steel": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "crane-s-echoing-call": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "crescent-pike": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "crimson-moon-s-semblance": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "dark-iron-sword": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "dawning-frost": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "deathmatch": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "debate-club": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "dialogues-of-the-desert-sages": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "disaster-and-remorse": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "dodoco-tales": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "dragon-s-bane": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "dragonspine-spear": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "earth-shaker": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "elegy-for-the-end": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "emerald-orb": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "end-of-the-line": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "engulfing-lightning": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "etherlight-spindlelute": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "everlasting-moonglow": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "eye-of-perception": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "fading-twilight": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "fang-of-the-mountain-king": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "favonius-codex": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "favonius-greatsword": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "favonius-lance": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "favonius-sword": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "favonius-warbow": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "ferrous-shadow": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "festering-desire": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "fillet-blade": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "finale-of-the-deep": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "flame-forged-insight": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "fleuve-cendre-ferryman": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "flower-wreathed-feathers": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "flowing-purity": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "flute-of-ezpitzal": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "footprint-of-the-rainbow": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "forest-regalia": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "fractured-halo": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "freedom-sworn": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "frostbearer": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "fruit-of-fulfillment": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "fruitful-hook": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "gest-of-the-mighty-wolf": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "golden-frostbound-oath": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "hakushin-ring": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "halberd": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "hamayumi": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "haran-geppaku-futsu": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "harbinger-of-dawn": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "hunter-s-path": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "ibis-piercer": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "iron-sting": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "jadefall-s-splendor": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "kagotsurube-isshin": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "kagura-s-verity": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "katsuragikiri-nagamasa": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "key-of-khaj-nisut": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "king-s-squire": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "kitain-cross-spear": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "light-of-foliar-incision": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "lightbearing-moonshard": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lion-s-roar": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "lithic-blade": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "lithic-spear": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lost-prayer-to-the-sacred-winds": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lumidouce-elegy": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "luxurious-sea-lord": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "magic-guide": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "mailed-flower": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "makhaira-aquamarine": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "mappa-mare": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "master-key": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "memory-of-dust": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "messenger": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "missive-windspear": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "mistsplitter-reforged": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "mitternachts-waltz": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "moonpiercer": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "moonweaver-s-dawn": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "mountain-bracing-bolt": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "mouun-s-moon": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "nightweaver-s-looking-glass": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "nocturne-s-curtain-call": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "oathsworn-eye": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "otherworldly-story": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "peak-patrol-song": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "polar-star": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "portable-power-saw": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "predator": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "primordial-jade-cutter": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "primordial-jade-winged-spear": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "prospector-s-drill": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "prospector-s-shovel": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "prototype-amber": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "prototype-archaic": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "prototype-crescent": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "prototype-rancour": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "prototype-starglitter": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "rainbow-serpent-s-rain-bow": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "rainslasher": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "range-gauge": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "raven-bow": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "recurve-bow": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "redhorn-stonethresher": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "reliquary-of-truth": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "rightful-reward": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "ring-of-yaxche": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "royal-bow": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "royal-greatsword": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "royal-grimoire": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "royal-longsword": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "royal-spear": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "rust": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sacrificer-s-staff": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "sacrificial-bow": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "sacrificial-fragments": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sacrificial-greatsword": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "sacrificial-jade": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sacrificial-sword": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sapwood-blade": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "scion-of-the-blazing-sun": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sequence-of-solitude": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "serenity-s-call": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "serpent-spine": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sharpshooter-s-oath": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "silvershower-heartstrings": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "skyrider-greatsword": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "skyrider-sword": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "skyward-atlas": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "skyward-blade": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "skyward-harp": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "skyward-pride": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "skyward-spine": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "slingshot": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "snare-hook": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "snow-tombed-starsilver": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "solar-pearl": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "song-of-broken-pines": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "song-of-stillness": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "splendor-of-tranquil-waters": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "staff-of-homa": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "staff-of-the-scarlet-sands": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "starcaller-s-watch": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "sturdy-bone": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "summit-shaper": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sunny-morning-sleep-in": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "surf-s-up": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sword-of-descension": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "sword-of-narzissenkreuz": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "symphonist-of-scents": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "talking-stick": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "tamayuratei-no-ohanashi": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "the-alley-flash": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "the-bell": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "the-black-sword": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "the-daybreak-chronicles": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "the-dockhand-s-assistant": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "the-first-great-magic": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "the-flute": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "the-stringless": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "the-unforged": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "the-viridescent-hunt": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "the-widsith": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "thrilling-tales-of-dragon-slayers": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "thundering-pulse": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "tidal-shadow": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "tome-of-the-eternal-flow": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "toukabou-shigure": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "traveler-s-handy-sword": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "tulaytullah-s-remembrance": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "twin-nephrite": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "uraku-misugiri": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "verdict": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "vivid-notions": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "vortex-vanquisher": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "wandering-evenstar": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "wavebreaker-s-fin": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "waveriding-whirl": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "white-iron-greatsword": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "white-tassel": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "whiteblind": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "windblume-ode": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "wine-and-song": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "wolf-fang": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "wolf-s-gravestone": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "xiphos-moonlight": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  }
};
