/** Auto-generated by packages/dataset/scripts/gen-material-domains.mts — do not edit by hand.
 * Domain + weekday rotation for each domain-farmed material, for the Farmable calendar (D). */
export interface MaterialDomain {
  domain: string;
  days: string[];
  kind: "talent" | "weapon";
}
export const MATERIAL_DOMAINS: Record<string, MaterialDomain> = {
  "Afterglow of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Fragment": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Inheritance": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Replica": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Artful Device Wish": {
    "domain": "Domain of Forgery: Radiant Splendor",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Aureate Radiance of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Bit of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blaze of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Hesitance": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Resolve": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Splendor": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Blazing Sacrificial Heart's Terror": {
    "domain": "Domain of Forgery: Scrying Shadows",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Broken Fang": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Cracked Tooth": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Milk Tooth": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Boreal Wolf's Nostalgia": {
    "domain": "Domain of Forgery: Submerged Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Broken Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Chains of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Chapter of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Chunk of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Copper Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Coral Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Debris of Decarabian's City": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Decadence of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Demeanor of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Desolation of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Delirious Divinity of the Sacred Lord": {
    "domain": "Domain of Forgery: Attentive Observation",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Divine Body from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Dream of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Dream of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Dross of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Echo of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Echo of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Ember of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Essence of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Fetters of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Flare of Long Night Flint": {
    "domain": "Domain of Forgery: Prayers Sung",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Fragment of Decarabian's Epic": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Fragment of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Golden Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Golden Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Golden Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Grain of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Guide to Admonition": {
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Ballad": {
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Conflict": {
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Contention": {
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Diligence": {
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Elegance": {
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Elysium": {
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Equity": {
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Freedom": {
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Gold": {
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Ingenuity": {
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Justice": {
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Kindling": {
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Light": {
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Moonlight": {
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Order": {
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Praxis": {
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Prosperity": {
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Resistance": {
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Transience": {
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Guide to Vagrancy": {
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Iron Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Jade Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Jeweled Branch of a Distant Sea": {
    "domain": "Domain of Forgery: Sunken Sands",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Luminous Sands from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Lustrous Stone from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the Kijin": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the One-Horned": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the Tiger's Bite": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mask of the Wicked Lieutenant": {
    "domain": "Domain of Forgery: Sand Burial",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Gold Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Lead Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Mercury Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Mist Veiled Primo Elixir": {
    "domain": "Domain of Forgery: Thundering Ruins",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Movement of an Ancient Chord": {
    "domain": "Domain of Forgery: Robotic Ruse",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Affection": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Joy": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Valor": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Narukami's Wisdom": {
    "domain": "Domain of Forgery: Altar of Sands",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Augury": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Consideration": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Premonition": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Night-Wind's Mystic Revelation": {
    "domain": "Domain of Forgery: Estimation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Kindness": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Mourning": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Reminiscence": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oasis Garden's Truth": {
    "domain": "Domain of Forgery: Obsession",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Oblation of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Olden Days of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Philosophies of Admonition": {
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Ballad": {
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Conflict": {
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Contention": {
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Diligence": {
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Elegance": {
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Elysium": {
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Equity": {
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Freedom": {
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Gold": {
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Ingenuity": {
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Justice": {
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Kindling": {
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Light": {
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Moonlight": {
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Order": {
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Praxis": {
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Prosperity": {
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Resistance": {
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Transience": {
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Philosophies of Vagrancy": {
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Piece of Aerosiderite": {
    "domain": "Domain of Forgery: Trial Grounds of Thunder",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Relic from Guyun": {
    "domain": "Domain of Forgery: Thundercloud Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Remnant Glow of Scorching Might": {
    "domain": "Domain of Forgery: Leading Karma",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Scattered Piece of Decarabian's Dream": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Shackles of the Dandelion Gladiator": {
    "domain": "Domain of Forgery: Ruins of Thirsting Capital",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Silver Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Silver Talisman of the Forest Dew": {
    "domain": "Domain of Forgery: Tainted Clouds",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Spring of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Sublimation of Pure Sacred Dewdrop": {
    "domain": "Domain of Forgery: Artisanship",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Sundered Glory of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Teachings of Admonition": {
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Ballad": {
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Conflict": {
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Contention": {
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Diligence": {
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Elegance": {
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Elysium": {
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Equity": {
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Freedom": {
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Gold": {
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Ingenuity": {
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Justice": {
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Kindling": {
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Light": {
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Moonlight": {
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Order": {
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Praxis": {
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Prosperity": {
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Resistance": {
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Transience": {
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Teachings of Vagrancy": {
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "talent"
  },
  "Tile of Decarabian's Tower": {
    "domain": "Domain of Forgery: City of Reflections",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Unyielding Delusion of the Far-North Scions": {
    "domain": "Domain of Forgery: Lunar Oblation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  },
  "Wine Goblet of the Pristine Sea": {
    "domain": "Domain of Forgery: Curious Contraptions",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ],
    "kind": "weapon"
  }
};

/** Each character's talent-book domain, for the Farmable calendar. */
export const CHARACTER_TALENT_DOMAINS: Record<string, { book: string; domain: string; days: string[] }> = {
  "aino": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "albedo": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "alhaitham": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "aloy": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "amber": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "arataki-itto": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "arlecchino": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "baizhu": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "barbara": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "beidou": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "bennett": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "candace": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "charlotte": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "chasca": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "chevreuse": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "chiori": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "chongyun": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "citlali": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "clorinde": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "collei": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "columbina": {
    "book": "Philosophies of Moonlight",
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "cyno": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "dahlia": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "dehya": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "diluc": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "diona": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "dori": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "durin": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "emilie": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "escoffier": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "eula": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "faruzan": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "fischl": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "flins": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "freminet": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "furina": {
    "book": "Philosophies of Justice",
    "domain": "Domain of Mastery: Admonishing Engraving",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "gaming": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "ganyu": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "gorou": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "hu-tao": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "iansan": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "ifa": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "illuga": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "ineffa": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "jahoda": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "jean": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kachina": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "kaedehara-kazuha": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kaeya": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "kamisato-ayaka": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kamisato-ayato": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kaveh": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "keqing": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "kinich": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kirara": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "klee": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "kujou-sara": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "kuki-shinobu": {
    "book": "Philosophies of Elegance",
    "domain": "Domain of Mastery: Thundering Valley",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "lan-yan": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "lauma": {
    "book": "Philosophies of Moonlight",
    "domain": "Domain of Mastery: Fallen City",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "layla": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "linnea": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lisa": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lohen": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "lynette": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "lyney": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "mavuika": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "mika": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "mona": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "mualani": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "nahida": {
    "book": "Philosophies of Ingenuity",
    "domain": "Domain of Mastery: Witticism",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "navia": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "nefer": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "neuvillette": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "nicole": {
    "book": "Philosophies of Elysium",
    "domain": "Domain of Mastery: Shadowed Legacy",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "nilou": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "ningguang": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "noelle": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "ororon": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "prune": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "qiqi": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "raiden-shogun": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "razor": {
    "book": "Philosophies of Resistance",
    "domain": "Domain of Mastery: Frozen Abyss",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "rosaria": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sandrone": {
    "book": "Philosophies of Vagrancy",
    "domain": "Domain of Mastery: Overturned Roost",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sangonomiya-kokomi": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sayu": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "sethos": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "shenhe": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "shikanoin-heizou": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sigewinne": {
    "book": "Philosophies of Equity",
    "domain": "Domain of Mastery: Rhyming Rhythm",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "skirk": {
    "book": "Philosophies of Contention",
    "domain": "Domain of Mastery: Sublime Turning",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "sucrose": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "tartaglia": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "thoma": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "tighnari": {
    "book": "Philosophies of Admonition",
    "domain": "Domain of Mastery: Full Moon",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "varesa": {
    "book": "Philosophies of Conflict",
    "domain": "Domain of Mastery: Return",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "varka": {
    "book": "Philosophies of Freedom",
    "domain": "Domain of Mastery: Frosted Altar",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "venti": {
    "book": "Philosophies of Ballad",
    "domain": "Domain of Mastery: Realm of Slumber",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "wanderer": {
    "book": "Philosophies of Praxis",
    "domain": "Domain of Mastery: Basket of Discipline",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "wriothesley": {
    "book": "Philosophies of Order",
    "domain": "Domain of Mastery: Chiming Recitation",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "xiangling": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "xianyun": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "xiao": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "xilonen": {
    "book": "Philosophies of Kindling",
    "domain": "Domain of Mastery: Myriad Illusions",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "xingqiu": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "xinyan": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "yae-miko": {
    "book": "Philosophies of Light",
    "domain": "Domain of Mastery: Vine-Infested Ruins",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "yanfei": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "yaoyao": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "yelan": {
    "book": "Philosophies of Prosperity",
    "domain": "Domain of Mastery: Altar of Flames",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "yoimiya": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "yumemizuki-mizuki": {
    "book": "Philosophies of Transience",
    "domain": "Domain of Mastery: Reign of Violet",
    "days": [
      "Monday",
      "Thursday",
      "Sunday"
    ]
  },
  "yun-jin": {
    "book": "Philosophies of Diligence",
    "domain": "Domain of Mastery: Heart of the Flames",
    "days": [
      "Tuesday",
      "Friday",
      "Sunday"
    ]
  },
  "zhongli": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  },
  "zibai": {
    "book": "Philosophies of Gold",
    "domain": "Domain of Mastery: Circle of Embers",
    "days": [
      "Wednesday",
      "Saturday",
      "Sunday"
    ]
  }
};
